[governance]
slug = "pole"
name = "Pole"
address = "3QdRG4feNfDqZ3GpSVGwW6hnSHb7AZ5BAcoKCpV9t2xr"
description = "Leveraged Yield Aggregator on Solana"

[governance.token]
address = "PoLEXM5xikzieXENFvP7WwHJPorcFiCUVuMo9BAGZT3"

[links]
website = "https://pole.finance"
app = "https://app.pole.finance"

[quarry]
rewarder = "3ahWtCwoyv4HHYdDtSzSPzD8DDo6jJKqEmPJrdztFnw4"

[quarry.gauge]
gaugemeister = "GbaiXZj8qmBA6aRScfDTx23K9VX2AgQqfJ74qdTtDHUr"
