[governance]
slug = "mnde"
name = "Marinade"
address = "3mnaXERbCiKkj4XLgpv682YK3o5Cjqti1NxRyoVNLnJp"
description = "Liquidity staking to secure and decentralize Solana"
iconURL = "https://raw.githubusercontent.com/marinade-finance/liquid-staking-program/main/Docs/img/MNDE.png"

[governance.token]
address = "MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey"
name = "Marinade Protocol Token"
symbol = "MNDE"
decimals = 9
logoURI = "https://raw.githubusercontent.com/marinade-finance/liquid-staking-program/main/Docs/img/MNDE.png"

[mnde-nft-locker]
address = "rLmyBAjCYR1MNc3KSG77y5XXT2DuMxkcxfqLYvjjJCs"
creators = ["6jG2QcwaJPFS8Y9SzgH2kfKPj6ERhLi9RVtH8kRahj4j"]
docs = "https://docs.marinade.finance/governance"
app = "https://dev.marinade.finance/app/mnde"

[[nft-locker-gauges]]
label = "Validator"
docs = "https://docs.marinade.finance/governance/gauges"
address = "mvgmBamY7hDWxLNGLshMoZn8nt2P8tKnKhaBeXMVajZ"
stateAccount = "8szGkuLTAux9XMgZ2vtY39jVSowEcpBfFfD8hXSEqdGC"

[proposals]
notice = """\
To create a proposal, first make a post on the [Marinade Governance Forum](https://forum.marinade.finance/).\n\n
Once you have determined that there is sufficient community support, add the link to the discussion thread and create a proposal.
"""
discussion = { required = true, link = "https://forum.marinade.finance/", prefix = "https://forum.marinade.finance/t/" }

[links]
website = "https://marinade.finance"
app = "https://marinade.finance/app/staking"
forum = "https://forum.marinade.finance"
discord = "https://discord.com/invite/6EtUf4Euu6"
github = "https://github.com/marinade-finance"
medium = "https://medium.com/marinade-finance"
twitter = "https://twitter.com/marinadeFinance"
